# Generated by Django 4.2 on 2023-05-02 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_cad_user', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usuarios',
            new_name='Usuario',
        ),
    ]
